name: 'Libraries Search Recipe'
description: 'Basic needs and structure for headless search.'
type: module
install:
  # Contrib
  - search_api 
  - search_api_solr
  - facets
  - search_api_decoupled
  - search_web_components

